name: CI for 5.x

on:
  push:
    branches: [ 5.x ]
  pull_request:
    branches: [ 5.x ]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test-mysql.yml@master
    with:
      os: 'ubuntu-latest'
      version: '16, 18, 20, 22'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
